### ISSUE TITLE
Summarize experience

### ISSUE THREAD

**Issue by hawkw** [hawkw/cs383s2015-lab4#7]
Comment on
- [x] "the biggest learning takeaways from the assignment"
- [x] "any challenges that you have encountered"

**Comment by hawkw** [comment]
This is still needed for today. I guess I'll do it since I can't get in touch with SJ.

**Comment by sjguillaume** [comment]
Hey, 
I am heading to the lab in just a minute!

**Comment by hawkw** [comment]
Okay, if you want to write responses to this question, I can add them to the [notebook](http://nbviewer.ipython.org/github/hawkw/cs383s2015-lab4/blob/master/Analysis.ipynb) when you're done!

**Comment by sjguillaume** [comment]
Takeaways from the assignment are how to change an agent's learning strategy to improve performance over time.  To implement this, the agents were given a reward when they were active and not arrested, and if they were caught they were given a negative reward.  The agent then uses this reinforcement to decide in the future what action to take based on their memory.  

Challenges encountered over the course of this lab were mainly in creating the rebellion strategy for the population.  The learning strategy was difficult to implement because the agents appeared to have learned not to rebel for a short period of time, however this learning did not become a trend.  This meant to us that the agents were not learning the strategy because their performance was remaining constant within a range.
